name: multi-job-workflow
on: push
jobs:
  test_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay library
        run: sudo apt-get install cowsay -y
      - name: Run Cowsay command
        run: cowsay -f dragon "I am a DRAGON" >> dragon.txt
      - uses: actions/upload-artifact@v4
        with:
          name: dragon-text
          path: dragon.txt
  test_job_2:
    needs: test_job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: dragon-text
      - name: Check files existance
        run: grep -i "dragon" dragon.txt
  test_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: dragon-text
      - name: Display content of file
        run: cat dragon.txt
      - name: List
        run: ls -ltra
