name: My Workflow

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Good evening!!"
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: List directory
        run: ls
      - name: Read
        run: cat README.md
